apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-synthetic-service
  labels:
    {{- include "dynatrace-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
